# -*- coding: utf-8 -*-
"""Bayesian_Inference_Assignment_e22024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1McaN7Vgq1Nc0Hkbm-0FwlzTeVJknOxzg

# Q. Bayesian Estimation of a User Ability Parameter from Item Responses

An online learning platform presents a user with a sequence of $n$ multiple-choice questions **one at a time**. Each question is either answered correctly or incorrectly, allowing the platform to update its estimate of the user's ability dynamically after every response.

Let $Y_i$ denote the user's response to the $i$-th item encountered:

$$Y_i=
\begin{cases}
1, & \text{if the user answers item } i \text{ correctly},\\
0, & \text{if the user answers item } i \text{ incorrectly}.
\end{cases}$$

The platform assumes that the probability of a correct response is governed by a two-parameter logistic (2PL) item response model. Specifically, conditional on the user's latent ability parameter $\Theta=\theta$, the response probability for item $i$ is:

$$P(Y_i=1\mid \Theta=\theta)=p_i(\theta)=\frac{1}{1+e^{-a_i(\theta-b_i)}},$$

where $a_i>0$ is the known discrimination parameter, and $b_i$ is the known difficulty parameter of item $i$.

Let $\mathbf{y}^{(k)} = (y_1, y_2, \dots, y_k)$ represent the **running vector of observed responses** up to the current step $k$ (where $1 \le k \le n$).

Before observing any responses, the platform initializes the user's latent ability estimate with a standard normal prior distribution:

$$f_{\Theta}^{(0)}(\theta) = \frac{1}{\sqrt{2\pi}} \exp\left(-\frac{\theta^2}{2}\right) \quad \text{implying} \quad \Theta \sim \mathscr{N}(0,1).$$

As the user progresses, the posterior distribution at step $k-1$ serves as the prior distribution for step $k$.

---

### Tasks

1. **Visualizing the Mechanics:** Plot $P(Y_i=1\mid \Theta=\theta)$ vs $\theta$ using Plotly for two distinct values of $a_i$, where one of those $a_i$ values is paired with three different difficulty values of $b_i$. Interpret how moving $b_i$ shifts the curve horizontally.
2. **Sequential Likelihood Contribution:** Write down the likelihood contribution $L(y_k \mid \theta)$ of a *single* new response $y_k$ at step $k$, given the latent ability $\theta$. Then, write down the joint likelihood function for the running history vector $\mathbf{y}^{(k)}$.
3. **Mathematical Formulation of the Running Update:** Write down the recursive relationship for the posterior density at step $k$, denoted $f_{\Theta \mid \mathbf{Y}^{(k)}}(\theta \mid \mathbf{y}^{(k)})$, up to a proportionality constant, using the prior state $f_{\Theta \mid \mathbf{Y}^{(k-1)}}(\theta \mid \mathbf{y}^{(k-1)})$ and the new observation $y_k$.
4. **Dynamic Shifting:** Explain how a correct answer ($y_k = 1$) to a highly difficult item (large $b_k$) mathematically shifts the peak of the running posterior density distribution relative to the previous step.
5. **Tracking Certainty and Sharpness:** Explain how the discrimination parameter $a_k$ of the current item alters the variance (or "sharpness") of the distribution during a running update. What happens when $a_k$ is very large versus very small?
6. **Numerical Implementation of a Running Grid:** Describe a algorithmic approach to numerically approximate and maintain this running posterior density function on a fixed grid of $\theta$-values. Explicitly state how you would perform the sequential normalization step computationally after an item is answered.


7. **Evaluating Convergence over the Timeline:** Suppose the user's true, hidden latent ability is $\theta_{\text{true}} = 0.75$. Write a Python script that extends your previous grid simulation to track the performance of the running estimators over a sequence of $n = 20$ items.
* **Simulate Responses:** Dynamically generate the user's responses $y_k \in \{0, 1\}$ at each step by comparing a random draw from a Uniform distribution $U(0,1)$ against the true response probability $p_k(\theta_{\text{true}})$. Give each item a random difficulty $b_k \sim \mathscr{N}(0, 1)$ and a random discrimination $a_k \sim \text{Uniform}(0.5, 2.0)$.
* **Track Estimators:** At each step $k$, calculate and store the running Posterior Mean ($\widehat{\theta}_{\mathrm{Bayes}}^{(k)}$) and the running Maximum A Posteriori ($\widehat{\theta}_{\mathrm{MAP}}^{(k)}$) estimate.
* **Visualize:** Use Plotly to create a single line chart showing the progression of both estimators from step $0$ to $20$. Add a static horizontal reference line at $y = 0.75$ representing $\theta_{\text{true}}$.
* **Analysis:** Briefly explain how the distance between your estimators and $\theta_{\text{true}}$ changes as $k$ increases, and interpret what this implies about the platform's confidence in its measurement.

### Task 1

Visualizing the Mechanics & Horizontal ShiftsThe probability of a correct response under the 2PL model is given by:$$p_i(\theta) = \frac{1}{1 + e^{-a_i(\theta - b_i)}}$$
"""

import numpy as np
import plotly.graph_objects as go

# Define theta range
theta = np.linspace(-4, 4, 300)

def p_2pl(theta, a, b):
    return 1 / (1 + np.exp(-a * (theta - b)))

# Configurations: [a_i, b_i, label]
configs = [
    (1.0, -1.0, "a=1.0, b=-1.0 (Easy)"),
    (1.0,  0.0, "a=1.0, b=0.0 (Medium)"),
    (1.0,  1.0, "a=1.0, b=1.0 (Hard)"),
    (2.5,  0.0, "a=2.5, b=0.0 (High Discrimination)")
]

fig = go.Figure()
for a, b, label in configs:
    fig.add_trace(go.Scatter(x=theta, y=p_2pl(theta, a, b), mode='lines', name=label))

fig.update_layout(
    title="2PL Item Response Theory Curve Mechanics",
    xaxis_title="Latent Ability (θ)",
    yaxis_title="Probability of Correct Response P(Y_i=1 | θ)",
    template="plotly_dark"
)
fig.show()

"""### Task 2: Sequential Likelihood & Joint History

1. Single Item Likelihood ContributionFor an individual observed response $y_k \in \{0, 1\}$ at sequence step $k$, the likelihood contribution given the latent ability $\theta$ is modeled as a Bernoulli trial:$$L(y_k \mid \theta) = [p_k(\theta)]^{y_k} [1 - p_k(\theta)]^{1 - y_k}$$
2. Joint Likelihood FunctionAssuming local (conditional) independence of item responses given the user's true ability $\theta$, the joint likelihood for the running response history vector $y^{(k)} = (y_1, y_2, \dots, y_k)$ is the product of individual likelihood expressions:$$L(y^{(k)} \mid \theta) = \prod_{i=1}^{k} [p_i(\theta)]^{y_i} [1 - p_i(\theta)]^{1 - y_i}$$

###Task 3: Mathematical Formulation of the Running Update

By applying Bayes' Theorem sequentially, the posterior distribution at step $k-1$ serves directly as the prior distribution for step $k$. Up to a normalization constant, the recursive relationship is defined as:$$f_{\Theta \mid Y^{(k)}}(\theta \mid y^{(k)}) \propto L(y_k \mid \theta) \cdot f_{\Theta \mid Y^{(k-1)}}(\theta \mid y^{(k-1)})$$Substituting the Bernoulli likelihood contribution:$$f_{\Theta \mid Y^{(k)}}(\theta \mid y^{(k)}) \propto \left( [p_k(\theta)]^{y_k} [1 - p_k(\theta)]^{1 - y_k} \right) \cdot f_{\Theta \mid Y^{(k-1)}}(\theta \mid y^{(k-1)})$$

###Task 4: Dynamic Shifting


When a user successfully answers a highly difficult item ($y_k = 1$ with a large $b_k$):Likelihood Multiplier: The item's likelihood contribution curve $p_k(\theta)$ acts as a soft high-pass filter. Because $b_k$ is high, $p_k(\theta)$ evaluates close to $0$ for low values of $\theta$ and climbs toward $1$ only at high $\theta$ ranges.Posterior Modification: Multiplying the prior density state $f_{\Theta \mid Y^{(k-1)}}(\theta \mid y^{(k-1)})$ by this right-shifted step-like function suppresses the lower tail of the probability density.Resulting Shift: This suppression eliminates lower-ability mass, forcing the new normalized center of mass and the peak (the MAP estimate) to shift noticeably to the right.

### Task 5: Tracking Certainty and Sharpness

The discrimination parameter $a_k$ determines the slope and steepness of the 2PL curve, mapping directly to information gain:Very Large $a_k$ (High Discrimination): The single-item likelihood curve resembles a steep step function. Multiplying by this steep function sharply slices away inconsistent regions of the prior density, severely narrowing the distribution. This rapidly decreases the variance, resulting in a distinct "sharpening" of the posterior curve (high information gain/certainty).Very Small $a_k$ (Low Discrimination): The likelihood curve becomes almost flat across the domain. Multiplying by a near-constant function leaves the shape of the previous posterior distribution virtually unchanged. The variance remains broad, indicating that the item added negligible certainty to the platform's profile assessment.

### Task 6: Numerical Implementation of a Running Grid

Because the combination of a Normal prior and a non-linear 2PL logistic likelihood does not produce an analytical closed-form solution (i.e., non-conjugate), we track the continuous density function over a discrete numerical mesh.

**Algorithmic Strategy**

* Grid Allocation: Define a finely spaced, bounded array of values representing $\theta$ (e.g., $N = 1000$ points across $[-4.0, 4.0]$) with step size $\Delta\theta$. Initialize your distribution tracker array posterior_grid at step $0$ evaluating the Gaussian PDF $\mathcal{N}(0,1)$ at each node.

* Pointwise Evaluation: Upon receiving a response $y_k$, compute the 2PL model probabilities vector $p_k(\theta)$ across all mesh points using the item parameters $a_k$ and $b_k$.

* Element-wise Update: Construct an unnormalized array by executing a direct element-by-element product:$$\text{unnormalized_posterior}_j = \left( [p_k(\theta_j)]^{y_k} [1 - p_k(\theta_j)]^{1 - y_k} \right) \times \text{posterior_grid}_j$$

* Trapezoidal/Riemann Normalization: To guarantee the total area sums to $1.0$, approximate the integral across the mesh numerically and normalize:
$$\text{Area} = \sum_{j=1}^{N} \text{unnormalized_posterior}_j \cdot \Delta\theta$$$$\text{posterior_grid}_j = \frac{\text{unnormalized_posterior}_j}{\text{Area}}$$

### Task 7: Evaluating Convergence over the Timeline
Generating synthetic responses based on $\theta_{\text{true}} = 0.75$, performs grid updates over 20 steps, and plots the estimation paths.
"""

import numpy as np
import plotly.graph_objects as go

# Set seed for reproducibility
np.random.seed(42)

# Simulation configuration
theta_true = 0.75
n_items = 20

# Setup numerical evaluation grid
grid_size = 2000
theta_grid = np.linspace(-4, 4, grid_size)
delta_theta = theta_grid[1] - theta_grid[0]

# Initialize Prior at Step 0: Standard Normal Distribution
prior_pdf = (1.0 / np.sqrt(2 * np.pi)) * np.exp(-0.5 * theta_grid**2)
current_posterior = prior_pdf / np.sum(prior_pdf * delta_theta)

# Tracking history structures (Step 0 tracks prior parameters)
est_bayes = [np.sum(theta_grid * current_posterior * delta_theta)]
est_map = [theta_grid[np.argmax(current_posterior)]]

# Item parameter generations
b_params = np.random.normal(0, 1, n_items)
a_params = np.random.uniform(0.5, 2.0, n_items)

# Sequential Evaluation Pipeline
for k in range(n_items):
    a_k = a_params[k]
    b_k = b_params[k]

    # Calculate response probability under true ability parameter
    p_true = 1.0 / (1.0 + np.exp(-a_k * (theta_true - b_k)))
    y_k = 1 if np.random.uniform(0, 1) < p_true else 0

    # Calculate likelihood curve across grid
    p_grid = 1.0 / (1.0 + np.exp(-a_k * (theta_grid - b_k)))
    likelihood = (p_grid ** y_k) * ((1.0 - p_grid) ** (1 - y_k))

    # Bayesian Update Step
    unnorm_post = likelihood * current_posterior
    current_posterior = unnorm_post / np.sum(unnorm_post * delta_theta)

    # Extract Point Estimates
    theta_hat_bayes = np.sum(theta_grid * current_posterior * delta_theta)
    theta_hat_map = theta_grid[np.argmax(current_posterior)]

    est_bayes.append(theta_hat_bayes)
    est_map.append(theta_hat_map)

# Interactively Plot Tracking Performance
steps = np.arange(0, n_items + 1)
fig = go.Figure()

fig.add_trace(go.Scatter(x=steps, y=est_bayes, mode='lines+markers', name='Posterior Mean (θ̂ Bayes)', line=dict(color='#636EFA')))
fig.add_trace(go.Scatter(x=steps, y=est_map, mode='lines+markers', name='MAP Estimate (θ̂ MAP)', line=dict(color='#EF553B', dash='dash')))
fig.add_trace(go.Scatter(x=steps, y=[theta_true]*len(steps), mode='lines', name='True Ability (θtrue = 0.75)', line=dict(color='#00CC96', width=3)))

fig.update_layout(
    title="Bayesian Estimator Convergence Tracking Over 20 Items",
    xaxis=dict(title="Sequence Timeline Step (k)", tickmode='linear', dtick=2),
    yaxis=dict(title="Ability Value Estimations"),
    template="plotly_dark",
    legend=dict(yanchor="bottom", y=0.01, xanchor="left", x=0.01)
)
fig.show()

"""# Q. Bayesian Tracking of Click-Through Rates (CTR) via Conjugate Beta-Binomial Updates

An e-commerce platform wants to optimize its recommendation engine by dynamically estimating the click-through rate (CTR) of a newly launched advertisement. Since user traffic arrives continuously, the platform updates its belief about the advertisement's performance **one impression at a time** rather than waiting for large batch updates.

Let $\Theta = \theta$ represent the true, hidden conversion rate (probability of a click) of the advertisement, where $\theta \in [0, 1]$.

Let $Y_k$ denote a single user's interaction with the advertisement at time step $k$:

$$Y_k =
\begin{cases}
1, & \text{if the user clicks the advertisement}, \\
0, & \text{if the user does not click the advertisement}.
\end{cases}$$

The platform assumes that conditional on the true conversion rate $\Theta = \theta$, each user interaction is an independent Bernoulli trial:

$$P(Y_k = 1 \mid \Theta = \theta) = \theta$$

Let $\mathbf{y}^{(k)} = (y_1, y_2, \dots, y_k)$ represent the **running vector of observed user interactions** up to the current impression step $k$ (where $1 \le k \le n$).

Before observing any data, the platform assigns a flexible **Beta distribution** as the initial prior over the unknown parameter $\Theta$:

$$f_{\Theta}^{(0)}(\theta) = \frac{1}{\mathrm{B}(\alpha_0, \beta_0)} \theta^{\alpha_0 - 1} (1 - \theta)^{\beta_0 - 1} \quad \text{implying} \quad \Theta \sim \text{Beta}(\alpha_0, \beta_0)$$

where $\mathrm{B}(\cdot, \cdot)$ is the Beta function acting as the normalizing constant. Under a sequential framework, the posterior distribution at step $k-1$ serves directly as the prior distribution for step $k$.

---

**Tasks**

**1. Structural Probability and Properties**
Plot the probability density function (PDF) of a $\text{Beta}(\alpha, \beta)$ distribution using Plotly for three distinct parameter pairs:

* Uninformative state: $(\alpha=1, \beta=1)$
* Right-skewed state: $(\alpha=2, \beta=8)$
* Left-skewed state: $(\alpha=8, \beta=2)$

Interpret how changing the balance between $\alpha$ and $\beta$ shifts the center of mass of the density function over the domain $[0, 1]$.

**2. Sequential Likelihood and Joint History**

Write down the mathematical likelihood contribution $L(y_k \mid \theta)$ of a *single* isolated response $y_k$ at step $k$, given the click probability $\theta$. Following this, express the joint likelihood function for the running history vector $\mathbf{y}^{(k)}$.

**3. Closed-Form Analytical Updates (Conjugacy)**

Using Bayes' Theorem, derive the recursive algebraic relationship for the posterior density at step $k$, denoted as $f_{\Theta \mid \mathbf{Y}^{(k)}}(\theta \mid \mathbf{y}^{(k)})$. Prove analytically that the posterior remains in the Beta family (**Beta-Binomial Conjugacy**) by explicitly writing down the closed-form update parameters $\alpha_k$ and $\beta_k$ as simple arithmetic updates of $\alpha_{k-1}$, $\beta_{k-1}$, and $y_k$. Also compute the **Posterior Mean** of the latent parameter $\Theta$ at time step $k$ (i.e. $\mathbb{E}[\Theta \mid \mathbf{Y}^{(k)}=\mathbf{y}^{(k)}]$).


**4. Dynamic Shifting Mechanics**

Explain how an observed click ($y_k = 1$) vs. a non-click ($y_k = 0$) shifts the peak of the running density distribution mathematically. Contrast this analytical framework against non-conjugate setups (such as the 2PL IRT model) where numerical grid integration is strictly required.

**5. Running Point Estimators**

State the exact closed-form equations used to evaluate the following point estimates at step $k$ directly from the updated shape parameters $\alpha_k$ and $\beta_k$:

* **Running Posterior Mean** ($\widehat{\theta}_{\mathrm{Bayes}}^{(k)}$)
* **Running Maximum A Posteriori** ($\widehat{\theta}_{\mathrm{MAP}}^{(k)}$)

**6. Performance Tracking and Convergence Analysis**

Suppose the advertisement's true, hidden click-through rate is $\theta_{\text{true}} = 0.35$. Write a Python script to track the performance of your closed-form sequential estimators over a timeline of $n = 100$ impressions:

* **Initialize State:** Set the base prior parameters to $\alpha_0 = 1, \beta_0 = 1$ (representing uniform initial uncertainty).
* **Simulate Responses:** Dynamically generate user responses $y_k \in \{0, 1\}$ at each step by comparing a random draw from a Uniform distribution $U(0,1)$ against $\theta_{\text{true}}$.
* **Track Estimators:** Loop through each step, update $\alpha_k$ and $\beta_k$ analytically, and store the computed values for $\widehat{\theta}_{\mathrm{Bayes}}^{(k)}$ and $\widehat{\theta}_{\mathrm{MAP}}^{(k)}$.
* **Visualize:** Use Plotly to create a single line chart showing the progression of both estimators from step $0$ to $100$. Add a static horizontal reference line at $y = 0.35$ representing $\theta_{\text{true}}$.
* **Analysis:** Explain how the distance between your estimators and $\theta_{\text{true}}$ responds as the sampling size $k$ approaches $100$. What does this imply about the accumulation of evidence over time relative to the choice of the initial prior?

###Task 1: Structural Probability and Properties
"""

import numpy as np
import scipy.stats as stats
import plotly.graph_objects as go

# Define the grid over the probability domain [0, 1]
theta_vals = np.linspace(0, 1, 500)

# Define configurations: (alpha, beta, label, color)
beta_configs = [
    (1, 1, "Uninformative State: Beta(1,1)", "#636EFA"),
    (2, 8, "Right-skewed State: Beta(2,8)", "#EF553B"),
    (8, 2, "Left-skewed State: Beta(8,2)", "#00CC96")
]

fig = go.Figure()

for alpha, beta, label, color in beta_configs:
    pdf_vals = stats.beta.pdf(theta_vals, alpha, beta)
    fig.add_trace(go.Scatter(
        x=theta_vals, y=pdf_vals,
        mode='lines', name=label,
        line=dict(color=color, width=3)
    ))

fig.update_layout(
    title="Beta Distribution PDF Under Different Alpha & Beta Profiles",
    xaxis_title="Click-Through Rate (θ)",
    yaxis_title="Probability Density",
    template="plotly_dark",
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)
fig.show()

"""### Task 2: Sequential Likelihood and Joint History

1. Single Isolated Response Likelihood ContributionFor a single binary observation $y_k \in \{0, 1\}$ at time step $k$, the likelihood contribution given the parameter $\theta$ follows a Bernoulli distribution:$$L(y_k \mid \theta) = \theta^{y_k} (1 - \theta)^{1 - y_k}$$
2. Joint Likelihood FunctionAssuming that each interaction is conditionally independent given the true click-through rate $\theta$, the joint likelihood for the history vector $y^{(k)} = (y_1, y_2, \dots, y_k)$ is the product of individual Bernoulli outcomes:$$L(y^{(k)} \mid \theta) = \prod_{i=1}^{k} \theta^{y_i} (1 - \theta)^{1 - y_i} = \theta^{\sum_{i=1}^k y_i} (1 - \theta)^{k - \sum_{i=1}^k y_i}$$

### Task 3: Closed-Form Analytical Updates (Conjugacy)

1. Derivation of Recursive Algebraic RelationshipBy Bayes' Theorem, the sequential posterior at step $k$ is proportional to the product of the incoming likelihood and the prior distribution (which is the posterior state at step $k-1$):$$f_{\Theta \mid Y^{(k)}}(\theta \mid y^{(k)}) \propto L(y_k \mid \theta) \cdot f_{\Theta \mid Y^{(k-1)}}(\theta \mid y^{(k-1)})$$Substituting the mathematical definitions:$$f_{\Theta \mid Y^{(k)}}(\theta \mid y^{(k)}) \propto \left( \theta^{y_k} (1 - \theta)^{1 - y_k} \right) \cdot \left( \frac{1}{B(\alpha_{k-1}, \beta_{k-1})} \theta^{\alpha_{k-1}-1} (1 - \theta)^{\beta_{k-1}-1} \right)$$Dropping constants independent of $\theta$:$$f_{\Theta \mid Y^{(k)}}(\theta \mid y^{(k)}) \propto \theta^{y_k + \alpha_{k-1} - 1} \cdot (1 - \theta)^{(1 - y_k) + \beta_{k-1} - 1}$$$$f_{\Theta \mid Y^{(k)}}(\theta \mid y^{(k)}) \propto \theta^{(\alpha_{k-1} + y_k) - 1} \cdot (1 - \theta)^{(\beta_{k-1} + 1 - y_k) - 1}$$

2. Proof of Beta Family Belonging (Conjugacy)The functional form above matches the kernel of a Beta distribution, explicitly proving Beta-Binomial Conjugacy. The direct arithmetic updates for the shape parameters are:$$\alpha_k = \alpha_{k-1} + y_k$$$$\beta_k = \beta_{k-1} + (1 - y_k)$$

3. Posterior MeanThe expected value of a variable distributed as $\text{Beta}(\alpha_k, \beta_k)$ yields the running posterior mean:$$E[\Theta \mid Y^{(k)} = y^{(k)}] = \frac{\alpha_k}{\alpha_k + \beta_k}$$

### Task 4: Dynamic Shifting Mechanics


1. Mathematical Shifting Behaviour

**Observed Click ($y_k = 1$):** Dynamically increments $\alpha_k$ by 1 while keeping $\beta_k$ constant. This increases the numerator of the distribution parameters, physically pulling the peak (mode) of the distribution to the right (towards a higher CTR).

**Observed Non-Click ($y_k = 0$):** Increments $\beta_k$ by 1 while keeping $\alpha_k$ constant. This increases the denominator's relative weight, dragging the density peak to the left (towards a lower CTR).

2. Contrast Against Non-Conjugate Setups

In conjugate frameworks (like Beta-Binomial), updates are exact, instantaneous, and analytical, requiring only basic arithmetic additions.In non-conjugate setups (such as the 2PL IRT model containing complex exponential parameters), multiplying the prior by the likelihood results in a functional form that does not belong to any known probability family. This completely eliminates the possibility of analytical updates, forcing platforms to deploy heavy numerical grid approximations or Markov Chain Monte Carlo (MCMC) simulations to compute updates sequentially.

### Task 5: Running Point Estimators

From the evaluated shape parameters $\alpha_k$ and $\beta_k$ at step $k$, point metrics are calculated exactly through these closed-form equations:

Running Posterior Mean ($\hat{\theta}^{(k)}_{\text{Bayes}}$):$$\hat{\theta}^{(k)}_{\text{Bayes}} = \frac{\alpha_k}{\alpha_k + \beta_k}$$
Running Maximum A Posteriori ($\hat{\theta}^{(k)}_{\text{MAP}}$):$$\hat{\theta}^{(k)}_{\text{MAP}} = \frac{\alpha_k - 1}{\alpha_k + \beta_k - 2} \quad \text{for } \alpha_k > 1, \beta_k > 1$$

### Task 6: Performance Tracking and Convergence Analysis
"""

import numpy as np
import plotly.graph_objects as go

# Establish tracking parameters and seed
np.random.seed(42)
theta_true = 0.35
n_impressions = 100

# Initialize Base Prior States: Beta(1, 1)
alpha_curr = 1
beta_curr = 1

# Performance arrays tracking timeline (Index 0 captures baseline prior state)
history_bayes = [alpha_curr / (alpha_curr + beta_curr)]
history_map = [0.5]  # Uniform distribution mode is mathematically undefined; defaulting to center

# Loop over the sequential stream
for k in range(1, n_impressions + 1):
    # Simulate Bernoulli response based on true parameter probability
    y_k = 1 if np.random.uniform(0, 1) < theta_true else 0

    # Conjugate exact closed-form update logic
    alpha_curr += y_k
    beta_curr += (1 - y_k)

    # Calculate point metrics
    theta_bayes = alpha_curr / (alpha_curr + beta_curr)
    theta_map = (alpha_curr - 1) / (alpha_curr + beta_curr - 2) if (alpha_curr + beta_curr > 2) else 0.5

    # Store parameters
    history_bayes.append(theta_bayes)
    history_map.append(theta_map)

# Visualization construction via Plotly
timeline = np.arange(0, n_impressions + 1)
fig = go.Figure()

fig.add_trace(go.Scatter(x=timeline, y=history_bayes, mode='lines', name='Posterior Mean (θ̂ Bayes)', line=dict(color='#636EFA', width=2.5)))
fig.add_trace(go.Scatter(x=timeline, y=history_map, mode='lines', name='MAP Estimate (θ̂ MAP)', line=dict(color='#EF553B', dash='dash', width=2.5)))
fig.add_trace(go.Scatter(x=timeline, y=[theta_true]*len(timeline), mode='lines', name='True CTR (θtrue = 0.35)', line=dict(color='#00CC96', width=2)))

fig.update_layout(
    title="Bayesian Beta-Binomial CTR Convergence Simulation (100 Impressions)",
    xaxis=dict(title="Impression Evaluation Step (k)"),
    yaxis=dict(title="CTR Value Estimate", range=[0, 1]),
    template="plotly_dark",
    legend=dict(yanchor="bottom", y=0.01, xanchor="right", x=0.99)
)
fig.show()

"""---

### 10. Computational Simulation and Out-of-Sample Validation

Using the theoretical framework established in the previous parts, write a Python class named `GMMFinancialSegmenter` that implements a two-dimensional Gaussian Mixture Model (GMM) using `scikit-learn` and visualizes the results interactively using `Plotly`. Your implementation should fulfill the following criteria:

*   **Data Splitting and Scaling:** Accept a dataset containing two continuous features (e.g., mimicking financial behaviors like `PURCHASES` and `CREDIT_LIMIT`), standardize the features to handle variance scaling, and split the data into an 80% training set and a 20% validation/test set.
*   **EM Execution:** Fit a GMM with $K=3$ components on the training data using the Expectation-Maximization (EM) algorithm, printing whether the model successfully converged and the number of iterations required.
*   **Out-of-Sample Performance:** Compute and output the average log-likelihood score over the unseen test set to validate how well the learned density functions generalize to new data.
*   **Interactive Visualizations:** Implement methods to generate three distinct Plotly figures:
    1.  An empirical **2D Density Heatmap** of the raw training data with marginal distributions to inspect its underlying multimodal structure.
    2.  A **Training Assignment Plot** that overlays the training data points on top of a continuous contour map showing the maximum posterior responsibilities ($\\gamma_{ik}$) computed across a fine coordinate grid.
    3.  A **Test Assignment Plot** that replicates the contour boundary visualization but overlays out-of-sample test data points to expose the physical regions of cluster ambiguity.



Briefly evaluate the resulting plots. Explain how the continuous background contour map visually demonstrates the soft assignment expectation vector $\mathbb{E}[Z_i \mid X_i = x_{\text{grid}}]$ that you proved analytically in Part 3.

Use the dataset

https://www.kaggle.com/datasets/arjunbhasin2013/ccdatado the questions in this cell
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.mixture import GaussianMixture
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

class GMMFinancialSegmenter:
    def __init__(self, data_url, features=['PURCHASES', 'CREDIT_LIMIT'], random_state=42):
        """
        Initializes the segmenter, loads the data, cleans missing values,
        standardizes features, and splits into train/test sets.
        """
        self.features = features
        self.random_state = random_state

        # Load the CC GENERAL dataset directly
        print("Fetching and loading dataset...")
        df = pd.read_csv(data_url)

        # Handle potential missing values in features (e.g., CREDIT_LIMIT has minor NaNs)
        self.raw_data = df[features].dropna().reset_index(drop=True)

        # Data Splitting: 80% Train, 20% Test
        self.X_train_raw, self.X_test_raw = train_test_split(
            self.raw_data, test_size=0.20, random_state=self.random_state
        )

        # Standardization (Variance Scaling)
        self.scaler = StandardScaler()
        self.X_train = self.scaler.fit_transform(self.X_train_raw)
        self.X_test = self.scaler.transform(self.X_test_raw)

        # Placeholders for model components
        self.gmm = None
        self.grid_x = None
        self.grid_y = None
        self.grid_z = None

    def fit_gmm(self, k_components=3):
        """
        Fits a Gaussian Mixture Model using the EM algorithm.
        Prints convergence status and iterations.
        """
        print(f"\n--- Executing Expectation-Maximization (K={k_components}) ---")
        self.gmm = GaussianMixture(
            n_components=k_components,
            covariance_type='full',
            random_state=self.random_state
        )
        self.gmm.fit(self.X_train)

        print(f"Model Converged: {self.gmm.converged_}")
        print(f"Number of Iterations Required: {self.gmm.n_iter_}")

        # Precompute background coordinate grid for continuous contour visualization
        self._generate_coordinate_grid()

    def evaluate_test_performance(self):
        """
        Computes and outputs the average log-likelihood score over the unseen test set.
        """
        if self.gmm is None:
            raise ValueError("GMM must be fitted before evaluating performance.")

        avg_log_likelihood = self.gmm.score(self.X_test)
        print(f"\n--- Out-of-Sample Performance Evaluation ---")
        print(f"Average Log-Likelihood over the Test Set: {avg_log_likelihood:.4f}")
        return avg_log_likelihood

    def _generate_coordinate_grid(self, resolution=150):
        """Helper method to construct a fine 2D evaluation coordinate mesh grid."""
        x_min, x_max = self.X_train[:, 0].min() - 0.5, self.X_train[:, 0].max() + 0.5
        y_min, y_max = self.X_train[:, 1].min() - 0.5, self.X_train[:, 1].max() + 0.5

        self.grid_x = np.linspace(x_min, x_max, resolution)
        self.grid_y = np.linspace(y_min, y_max, resolution)
        grid_X, grid_Y = np.meshgrid(self.grid_x, self.grid_y)

        # Flatten the mesh to get coordinates for evaluation
        grid_coords = np.c_[grid_X.ravel(), grid_Y.ravel()]

        # Compute latent posterior responsibilities gamma_ik for each point on the grid
        responsibilities = self.gmm.predict_proba(grid_coords)

        # Determine index of cluster with maximum posterior responsibility
        max_resp_idx = np.argmax(responsibilities, axis=1)
        self.grid_z = max_resp_idx.reshape(grid_X.shape)

    def plot_density_heatmap(self):
        """1. Generates empirical 2D Density Heatmap of the training data with marginal distributions."""
        # NOTE: passing color_continuous_scale directly into px.density_heatmap while
        # marginal_x/marginal_y="histogram" are set raises a ValueError in current
        # Plotly versions, because the colorscale gets propagated to the marginal
        # histogram traces too (which don't accept a named colorscale as `marker.color`).
        # Fix: build the figure without color_continuous_scale, then apply the
        # colorscale only to the 2D histogram trace itself.
        fig = px.density_heatmap(
            x=self.X_train[:, 0],
            y=self.X_train[:, 1],
            marginal_x="histogram",
            marginal_y="histogram",
            labels={'x': f'Standardized {self.features[0]}', 'y': f'Standardized {self.features[1]}'},
            title="Empirical 2D Density Heatmap with Marginals (Training Data)",
            template="plotly_dark",
        )
        fig.update_traces(selector=dict(type="histogram2d"), colorscale="Viridis")
        fig.show()

    def plot_training_assignments(self):
        """2. Generates a Training Assignment Plot overlaid on the maximum posterior responsibilities contour map."""
        train_preds = self.gmm.predict(self.X_train)

        fig = go.Figure()

        # Continuous contour background mapping maximum responsibilities
        fig.add_trace(go.Contour(
            x=self.grid_x, y=self.grid_y, z=self.grid_z,
            colorscale="Tealrose", opacity=0.35, showscale=False, hoverinfo='skip'
        ))

        # Training scatter plot points colored by hard cluster assignment
        fig.add_trace(go.Scatter(
            x=self.X_train[:, 0], y=self.X_train[:, 1],
            mode='markers',
            marker=dict(color=train_preds, colorscale="Tealrose", size=5, line=dict(width=0.5, color='black')),
            text=[f"Cluster Label: {p}" for p in train_preds],
            name="Training Sample"
        ))

        fig.update_layout(
            title="GMM Cluster Assignment Boundaries Over Training Observations",
            xaxis_title=f"Standardized {self.features[0]}",
            yaxis_title=f"Standardized {self.features[1]}",
            template="plotly_dark"
        )
        fig.show()

    def plot_test_assignments(self):
        """3. Generates a Test Assignment Plot replicating the background contour with unseen test data."""
        test_preds = self.gmm.predict(self.X_test)

        fig = go.Figure()

        # Continuous contour background
        fig.add_trace(go.Contour(
            x=self.grid_x, y=self.grid_y, z=self.grid_z,
            colorscale="Tealrose", opacity=0.35, showscale=False, hoverinfo='skip'
        ))

        # Test scatter plot points colored by model expectations
        fig.add_trace(go.Scatter(
            x=self.X_test[:, 0], y=self.X_test[:, 1],
            mode='markers',
            marker=dict(color=test_preds, colorscale="Tealrose", size=6, symbol='diamond', line=dict(width=0.5, color='white')),
            text=[f"Predicted Cluster: {p}" for p in test_preds],
            name="Out-of-Sample Test Sample"
        ))

        fig.update_layout(
            title="GMM Cluster Assignment Boundaries Over Out-of-Sample Test Observations",
            xaxis_title=f"Standardized {self.features[0]}",
            yaxis_title=f"Standardized {self.features[1]}",
            template="plotly_dark"
        )
        fig.show()

# --- Execution Block for your Google Colab Notebook ---
if __name__ == "__main__":
    # URL to the raw dataset CSV hosted on GitHub.
    # NOTE: the original arjunbhasin2013/CC-CUSTOMER-DATA-ANALYSIS URL returns a
    # 404 (repo/path no longer exists). Swapped in a mirror that actually serves
    # the raw CSV.
    raw_data_url = "https://raw.githubusercontent.com/RAHULKASHYAP02/Credit-Card-Segmentation/master/CC%20GENERAL.csv"

    # Instantiate the Segmenter object
    segmenter = GMMFinancialSegmenter(data_url=raw_data_url)

    # Fit the Model via EM
    segmenter.fit_gmm(k_components=3)

    # Compute Generalization Performance Metric
    segmenter.evaluate_test_performance()

    # Display the interactive Plotly Figures
    segmenter.plot_density_heatmap()
    segmenter.plot_training_assignments()
    segmenter.plot_test_assignments()

"""###Evaluation and Analytical Interpretation

1. Plot Evaluation and Multimodal Density2D Density Heatmap: The distribution of data points shows a high concentration near the lower left quadrant (low purchases, low credit limits), with skewed tails moving outward. The marginal histograms uncover clear multimodality, confirming that a standard single Gaussian structure would underfit, justifying the use of a Gaussian Mixture Model ($K=3$) to capture discrete density pockets.Training and Test Assignment Plots: The model successfully separates the feature space into three main financial profiles: low-spending/low-limit clients, high-spending clients, and high-limit/conservative-spending clients. When viewing the out-of-sample test plot, most test points fall comfortably inside the color zones established during training, confirming stable classification parameters.

2. Analytical Connection to Soft Assignment ExpectationsThe continuous background contour maps display boundaries determined by evaluating:$$\gamma_{ik} = P(Z_i = k \mid X_i = x_{\text{grid}}) = \frac{\pi_k \mathcal{N}(x_{\text{grid}} \mid \mu_k, \Sigma_k)}{\sum_{j=1}^K \pi_j \mathcal{N}(x_{\text{grid}} \mid \mu_j, \Sigma_j)}$$Mathematically, the soft assignment expectation vector for a hidden categorical variable indicator vector $Z_i$ is equal to its posterior responsibility vector:$$E[Z_i \mid X_i = x_{\text{grid}}] = \begin{bmatrix} P(Z_i = 1 \mid X_i = x_{\text{grid}}) \\ P(Z_i = 2 \mid X_i = x_{\text{grid}}) \\ \vdots \\ P(Z_i = K \mid X_i = x_{\text{grid}}) \end{bmatrix} = \begin{bmatrix} \gamma_{i1} \\ \gamma_{i2} \\ \vdots \\ \gamma_{iK} \end{bmatrix}$$The background contour maps display the argmax of this expectation vector across every coordinate point:$$\text{Contour Color} = \arg\max_{k} E[Z_{ik} \mid X_i = x_{\text{grid}}]$$Where distinct color zones meet, the responsibilities are evenly split (e.g., $\gamma_{i1} \approx \gamma_{i2} \approx 0.5$). The visualization demonstrates that instead of rigid, hard-coded geometric cuts (like K-Means), the background boundary is derived directly from continuous underlying probability densities. This reveals exactly where the model faces maximum assignment ambiguity when evaluating new observations.

# Q Bayesian Estimations for Structural Health Monitoring via Bounded Grid Updates

In aerospace and civil engineering, Structural Health Monitoring (SHM) is critical for detecting damage before a catastrophic failure occurs. Consider an aircraft wing or a bridge girder equipped with specialized vibration sensors. Over time, environmental fatigue or dynamic impacts can cause micro-fractures, resulting in a reduction of the component's mechanical stiffness.

Let $\Theta = \theta$ represent the structural **remaining stiffness efficiency factor**, where $\theta$ is physically bounded to the interval:

$$\theta \in (0, 1]$$

* $\theta = 1.0$ indicates a perfectly pristine, undamaged structural component.
* $\theta \to 0$ signifies critical degradation or severe structural cracking.

Let $K_{\text{nominal}}$ be the known, baseline stiffness of the structural component when it is entirely healthy. At each sequential inspection time step $k$ (where $k = 1, 2, \dots, n$), a sensor collects a noisy experimental stiffness measurement $y_k$.

Engineers model the degradation physics via a non-linear relationship with multiplicative log-normal measurement noise to prevent non-physical negative values:

$$y_k = \theta \cdot K_{\text{nominal}} \cdot e^{\epsilon_k}, \qquad \epsilon_k \sim \mathscr{N}(0, \sigma^2)$$

where $\sigma$ is the standard deviation of the sensor noise in log-space.

Let $\mathbf{y}^{(k)} = (y_1, y_2, \dots, y_k)$ represent the **running history vector of observed sensor readings** up to the current inspection milestone. Before deploying the sensors, engineers utilize an initial prior distribution $f_{\Theta}^{(0)}(\theta)$ over the domain $(0, 1]$ based on historical manufacturing specifications. As the sensor stream arrives, the posterior distribution calculated at step $k-1$ serves directly as the prior distribution for step $k$.

---

### **Tasks**

#### **1. Prior Belief Boundaries**

Before data collection begins, engineers assume the component is highly likely to be healthy, modeling this using a bounded Beta distribution as the initial prior: $\Theta \sim \text{Beta}(8, 1.5)$.

* Plot this initial prior density function using Plotly over the restricted physical domain $\theta \in [0.01, 1.0]$.
* Calculate the expected prior stiffness efficiency $\mathbb{E}[\Theta^{(0)}]$ analytically. Explain why this specific distribution serves as an appropriate initial prior for an engineering component assumed to be healthy.

#### **2. Structural Likelihood Formulation**

Using the change of variables or properties of the log-normal distribution, write down the mathematical likelihood contribution $L(y_k \mid \theta)$ of a *single* continuous sensor measurement $y_k$ at inspection step $k$, given the true stiffness factor $\theta$. Following this, write down the joint likelihood function for the running history vector $\mathbf{y}^{(k)}$.

#### **3. Mathematical Formulation of the Non-Conjugate Grid Update**

Explain why an exact closed-form analytical solution for the posterior density $f_{\Theta \mid \mathbf{Y}^{(k)}}(\theta \mid \mathbf{y}^{(k)})$ does not exist when combining a Beta prior with this log-normal structural likelihood. Write down the recursive relationship for the posterior density at step $k$ up to a proportionality constant.

#### **4. Running Point Estimates**

Because a closed-form formula is unavailable, we must define point estimators through numerical integration. Write down the definite integral equations over the bounded domain $(0, 1]$ required to compute:

* The **Running Posterior Mean** ($\widehat{\theta}_{\mathrm{Bayes}}^{(k)}$)
* The **Running Maximum A Posteriori** ($\widehat{\theta}_{\mathrm{MAP}}^{(k)}$)

#### **5. Algorithmic Grid Approximation and Normalization**

Describe the step-by-step numerical procedure to maintain this distribution on a discrete grid of $\theta$-values. Explicitly state how you would handle the boundary limits computationally and how you would perform the sequential normalization step using the trapezoidal rule after a new sensor reading $y_k$ is observed.

#### **6. Performance Tracking and Degradation Convergence Analysis**

Suppose an impact occurs, and the true, hidden remaining stiffness drops to $\theta_{\text{true}} = 0.68$. Write a Python script using Plotly to simulate an engineered monitoring timeline across $n = 15$ continuous sensor measurements ($K_{\text{nominal}} = 50.0 \text{ kN/mm}$, $\sigma = 0.15$):

* **Simulate Sensor Stream:** Programmatically generate noisy sensor readings $y_k$ by drawing random values from the underlying log-normal physics model centered at $\theta_{\text{true}}$.
* **Track Estimators:** Loop sequentially through each step. At each step, update the unnormalized grid, normalize it via `np.trapezoid`, and compute both $\widehat{\theta}_{\mathrm{Bayes}}^{(k)}$ and $\widehat{\theta}_{\mathrm{MAP}}^{(k)}$.
* **Visualize Curves & Timeline:** Generate two plots:
1. A plot showing the progression of the full posterior density curves at milestones $k \in \{0, 1, 2, 5, 10, 15\}$.
2. A line chart tracking the convergence of both $\widehat{\theta}_{\mathrm{Bayes}}^{(k)}$ and $\widehat{\theta}_{\mathrm{MAP}}^{(k)}$ from step $0$ to $15$ against a horizontal reference line at $\theta_{\text{true}} = 0.68$.


* **Analysis:** Evaluate the behavior of the distribution. How many sensor readings did it take for the system to overcome the initially optimistic "healthy" prior and confidently isolate the 68% damage state? What does the narrowing of the density curves imply about structural safety thresholds?

### Task 1: Prior Belief Boundaries

**Expected Prior Stiffness Efficiency**\
The expected value of a standard Beta-distributed random variable $\Theta \sim \text{Beta}(\alpha, \beta)$ is analytically derived as:$$E[\Theta^{(0)}] = \frac{\alpha}{\alpha + \beta}$$Given your parameters $\alpha = 8$ and $\beta = 1.5$:$$E[\Theta^{(0)}] = \frac{8}{8 + 1.5} = \frac{8}{9.5} \approx 0.8421$$
"""

import numpy as np
import scipy.stats as stats
import plotly.graph_objects as go

# Bounded physical domain
theta_vals = np.linspace(0.01, 1.0, 500)
alpha_0, beta_0 = 8, 1.5

# Calculate Beta PDF
pdf_vals = stats.beta.pdf(theta_vals, alpha_0, beta_0)

fig = go.Figure()
fig.add_trace(go.Scatter(
    x=theta_vals, y=pdf_vals,
    mode='lines', name='Initial Prior Beta(8, 1.5)',
    line=dict(color='#636EFA', width=3)
))

fig.update_layout(
    title="Initial Prior Belief Density over Stiffness Efficiency (θ)",
    xaxis_title="Stiffness Efficiency Factor (θ)",
    yaxis_title="Probability Density",
    template="plotly_dark"
)
fig.show()

"""### Task 2: Structural Likelihood Formulation

**Single Measurement Likelihood Contribution**\

Given the measurement equation $y_k = \theta \cdot K_{\text{nominal}} \cdot e^{\epsilon_k}$ where $\epsilon_k \sim \mathcal{N}(0, \sigma^2)$, we apply a logarithmic change of variables. Taking the natural log yields:$$\ln(y_k) = \ln(\theta) + \ln(K_{\text{nominal}}) + \epsilon_k \implies \epsilon_k = \ln(y_k) - \ln(\theta \cdot K_{\text{nominal}})$$Since $\epsilon_k \sim \mathcal{N}(0, \sigma^2)$, the variable $y_k$ follows a log-normal distribution. The likelihood contribution $L(y_k \mid \theta)$ of a single observed continuous sensor measurement is:$$L(y_k \mid \theta) = \frac{1}{y_k \sigma \sqrt{2\pi}} \exp\left( -\frac{\left(\ln(y_k) - \ln(\theta \cdot K_{\text{nominal}})\right)^2}{2\sigma^2} \right)$$Joint History Likelihood FunctionAssuming that individual sensor observations are conditionally independent over time given the true underlying efficiency state $\theta$, the joint likelihood function for the running history vector $\mathbf{y}^{(k)} = (y_1, y_2, \dots, y_k)$ is the product of their individual likelihood components:$$L(\mathbf{y}^{(k)} \mid \theta) = \prod_{i=1}^{k} \frac{1}{y_i \sigma \sqrt{2\pi}} \exp\left( -\frac{\left(\ln(y_i) - \ln(\theta \cdot K_{\text{nominal}})\right)^2}{2\sigma^2} \right)$$

### Task 3: Mathematical Formulation of the Non-Conjugate Grid Update

**Why an Analytical Solution Does Not Exist**

An exact closed-form analytical solution is unavailable because the Beta distribution and the Log-Normal measurement likelihood do not form a conjugate pair. When multiplying the polynomial kernel of the Beta prior $\theta^{\alpha-1}(1-\theta)^{\beta-1}$ by the exponential-logarithmic form of the log-normal likelihood, the resulting function cannot be simplified into any known, standard parametric probability density family. The normalizer (the marginal likelihood integral in the denominator of Bayes' theorem) lacks a closed-form anti-derivative.

**Recursive Relationship**

By evaluating Bayes’ Theorem sequentially, the posterior state from the previous epoch $k-1$ serves directly as the prior distribution for step $k$. Up to a normalization proportionality constant, the recursive relationship is written as:$$f_{\Theta \mid \mathbf{Y}^{(k)}}(\theta \mid \mathbf{y}^{(k)}) \propto L(y_k \mid \theta) \cdot f_{\Theta \mid \mathbf{Y}^{(k-1)}}(\theta \mid \mathbf{y}^{(k-1)})$$Substituting our single-item log-normal structural likelihood:$$f_{\Theta \mid \mathbf{Y}^{(k)}}(\theta \mid \mathbf{y}^{(k)}) \propto \exp\left( -\frac{\left(\ln(y_k) - \ln(\theta \cdot K_{\text{nominal}})\right)^2}{2\sigma^2} \right) \cdot f_{\Theta \mid \mathbf{Y}^{(k-1)}}(\theta \mid \mathbf{y}^{(k-1)})$$(Note: Factors like $\frac{1}{y_k \sigma \sqrt{2\pi}}$ are omitted here since they do not depend on $\theta$ and are absorbed by the proportionality constant).

### Task 4: Running Point Estimates

Because we cannot evaluate the continuous distribution algebraically, point metrics must be computed using numerical standard definite integration across the strictly bounded parameter space $\theta \in (0,1]$:

1. Running Posterior Mean ($\hat{\theta}^{(k)}_{\text{Bayes}}$)$$\hat{\theta}^{(k)}_{\text{Bayes}} = E[\Theta \mid \mathbf{y}^{(k)}] = \frac{\int_{0}^{1} \theta \cdot f_{\Theta \mid \mathbf{Y}^{(k)}}(\theta \mid \mathbf{y}^{(k)}) \, d\theta}{\int_{0}^{1} f_{\Theta \mid \mathbf{Y}^{(k)}}(\theta \mid \mathbf{y}^{(k)}) \, d\theta}$$

2. Running Maximum A Posteriori ($\hat{\theta}^{(k)}_{\text{MAP}}$)$$\hat{\theta}^{(k)}_{\text{MAP}} = \arg\max_{\theta \in (0, 1]} f_{\Theta \mid \mathbf{Y}^{(k)}}(\theta \mid \mathbf{y}^{(k)})$$

###Task 5: Algorithmic Grid Approximation and Normalization

1. Grid Allocation: Define a closely spaced grid of $N$ discrete nodes across the bounded physical workspace $\theta \in [0.01, 1.0]$. The boundary limit is bounded computationally at $\theta = 0.01$ instead of $0$ to avoid numerical singularity failures when taking $\ln(\theta)$. Define a constant node delta interval $\Delta \theta$.

2. Prior Initialization: Evaluate the baseline structural density function $\text{Beta}(8, 1.5)$ pointwise over all nodes. Normalize this array using the trapezoidal rule so the total baseline integrated area equals exactly $1.0$.

3. Sequential Processing Pipeline: Upon collecting a new experimental sensor observation reading $y_k$:

* Compute the single-item likelihood array $L(y_k \mid \theta_j)$ point-by-point across all grid nodes $j$.
* Perform an element-wise array multiplication of the likelihood vector by the existing active posterior grid vector to get the unnormalized tracking vector:$$u_j = L(y_k \mid \theta_j) \times \text{posterior_grid}_j$$
* Trapezoidal Normalization: Compute the area under this unnormalized grid numerically:$$\text{Area} = \frac{\Delta \theta}{2} \sum_{j=1}^{grid\_size-1} (u_j + u_{j+1})$$
* Divide the unnormalized vector elements by this integrated scalar area to update the active posterior array state: $\text{posterior_grid}_j = \frac{u_j}{\text{Area}}$.

### Task 6: Performance Tracking and Degradation Convergence Analysis
"""

import numpy as np
import scipy.stats as stats
import plotly.graph_objects as go

# Fix random seeds for reproducible data generation
np.random.seed(42)

# Global Engineering Configurations
theta_true = 0.68
K_nominal = 50.0
sigma = 0.15
n_measurements = 15

# Set up numerical processing grid (boundary offset at 0.01 to prevent log(0))
grid_size = 2000
theta_grid = np.linspace(0.01, 1.0, grid_size)

# Step 0 Initializations: Prior Beta(8, 1.5)
prior_pdf = stats.beta.pdf(theta_grid, 8, 1.5)
# Base initialization via trapezoidal normalization
area_init = np.trapezoid(prior_pdf, theta_grid)
current_posterior = prior_pdf / area_init

# Arrays to keep historical track of point estimators
est_bayes = [np.trapezoid(theta_grid * current_posterior, theta_grid)]
est_map = [theta_grid[np.argmax(current_posterior)]]
milestones_curves = {0: current_posterior.copy()}

# Sequential Inspection Simulation Pipeline
for k in range(1, n_measurements + 1):
    # Simulate Sensor Stream based on log-normal physics model
    epsilon_k = np.random.normal(0, sigma)
    y_k = theta_true * K_nominal * np.exp(epsilon_k)

    # Calculate likelihood curve across grid
    # L(y_k | theta) ~ exp(- (ln(y_k) - ln(theta * K_nominal))^2 / (2 * sigma^2))
    ln_diff = np.log(y_k) - np.log(theta_grid * K_nominal)
    likelihood = np.exp(-(ln_diff ** 2) / (2 * (sigma ** 2)))

    # Non-conjugate multiplication update
    unnorm_posterior = likelihood * current_posterior

    # Sequential Normalization step using trapezoidal rule
    area_norm = np.trapezoid(unnorm_posterior, theta_grid)
    current_posterior = unnorm_posterior / area_norm

    # Extract Point Estimates
    theta_hat_bayes = np.trapezoid(theta_grid * current_posterior, theta_grid)
    theta_hat_map = theta_grid[np.argmax(current_posterior)]

    # Store records
    est_bayes.append(theta_hat_bayes)
    est_map.append(theta_hat_map)
    if k in [1, 2, 5, 10, 15]:
        milestones_curves[k] = current_posterior.copy()

# Plot 1: Full Posterior Density Progression Curves
fig1 = go.Figure()
colors = {0: '#636EFA', 1: '#EF553B', 2: '#00CC96', 5: '#AB63FA', 10: '#FFA15A', 15: '#19D3F3'}
for milestone, curve in milestones_curves.items():
    fig1.add_trace(go.Scatter(
        x=theta_grid, y=curve, mode='lines',
        name=f'Milestone k={milestone}', line=dict(color=colors[milestone], width=2.5)
    ))
fig1.update_layout(
    title="Posterior Density Function Curve Progression Across Milestones",
    xaxis_title="Stiffness Efficiency Factor (θ)", yaxis_title="Density",
    template="plotly_dark"
)
fig1.show()

# Plot 2: Convergence of Point Estimators
steps = np.arange(0, n_measurements + 1)
fig2 = go.Figure()
fig2.add_trace(go.Scatter(x=steps, y=est_bayes, mode='lines+markers', name='Posterior Mean (θ̂ Bayes)', line=dict(color='#636EFA')))
fig2.add_trace(go.Scatter(x=steps, y=est_map, mode='lines+markers', name='MAP Estimate (θ̂ MAP)', line=dict(color='#EF553B', dash='dash')))
fig2.add_trace(go.Scatter(x=steps, y=[theta_true]*len(steps), mode='lines', name='True Value (θtrue=0.68)', line=dict(color='#00CC96', width=3)))
fig2.update_layout(
    title="Bayesian Estimator Timeline Convergence Profile",
    xaxis=dict(title="Inspection Milestone Step (k)", tickmode='linear', dtick=1),
    yaxis=dict(title="Stiffness Factor Estimations"), template="plotly_dark"
)
fig2.show()

"""# Q. Gaussian Mixture Clustering as Conditional Updating

Consider a dataset
$$
x_1,x_2,\dots,x_n\in\mathbb R^d.
$$
We wish to cluster these observations into $K$ groups. Instead of assigning each point deterministically to a cluster at the beginning, we introduce a latent random variable
$$
C_i\in{1,\dots,K},
$$
where $C_i=k$ means that the observation $x_i$ belongs to cluster $k$.
Let the prior probability of cluster membership be
$$
P(C_i=k)=\phi_k,
$$
where
$$
\phi_k\ge 0,
\qquad
\sum_{k=1}^K \phi_k=1.
$$

Conditional on $C_i=k$, assume that the observation $X_i$ is generated from a multivariate Gaussian distribution:
$$
X_i\mid C_i=k
\sim
\mathscr N(\mu_k,\Sigma_k),
$$
where
$$
\mu_k\in\mathbb R^d,
\qquad
\Sigma_k\in\mathbb R^{d\times d}
$$
are the mean vector and covariance matrix of cluster $k$.

The model parameters
$$
\phi_k,\mu_k,\Sigma_k,
\qquad k=1,\dots,K,
$$
are assumed to be fixed but unknown.

---

1. Deriving the Marginal Density:
Using the law of total probability, show that the marginal density of $X_i$ is
$$
p(x_i)=\sum_{k=1}^K
\phi_k
\mathscr N(x_i\mid \mu_k,\Sigma_k).
$$
Explain why this density is called a Gaussian mixture density.

---

2. Deriving the Posterior Cluster Probability:
For a fixed observation $x_i$, use Bayes' rule to derive
$$
P(C_i=k\mid X_i=x_i)=\frac{
P(X_i=x_i\mid C_i=k)P(C_i=k)
}{
\sum_{j=1}^K P(X_i=x_i\mid C_i=j)P(C_i=j)
}.
$$
Then substitute the Gaussian model and the cluster prior to obtain
$$
P(C_i=k\mid X_i=x_i)=\frac{
\phi_k\mathscr N(x_i\mid \mu_k,\Sigma_k)
}{
\sum_{j=1}^K
\phi_j\mathscr N(x_i\mid \mu_j,\Sigma_j)
}.
$$
This quantity is called the responsibility of cluster $k$ for data point $x_i$, and is denoted by
$$
\gamma_{ik}=P(C_i=k\mid X_i=x_i).
$$
Explain why $\gamma_{ik}$ may be interpreted as a posterior probability of cluster membership.

---

3. One-Hot Encoding of the Latent Cluster Variable:
Now define a one-hot encoded latent random vector
$$
Z_i=
\begin{bmatrix}
Z_{i1}\\
Z_{i2}\\
\vdots\\
Z_{iK}
\end{bmatrix},
$$
where
$$
Z_{ik}=\begin{cases}
1, & \text{if } C_i=k,\\
0, & \text{otherwise}.
\end{cases}
$$
Show that
$$
\mathbb E[Z_{ik}\mid X_i=x_i]=P(C_i=k\mid X_i=x_i).
$$
Hence show that
$$
\mathbb E[Z_i\mid X_i=x_i]=\begin{bmatrix}
\gamma_{i1}\\
\gamma_{i2}\\
\vdots\\
\gamma_{iK}
\end{bmatrix}.
$$
Conclude that the soft cluster assignment in a Gaussian mixture model is precisely the conditional expectation
$$
\mathbb E[Z_i\mid X_i=x_i].
$$

---

4. From Soft Assignment to Hard Clustering:
The vector
$$
\mathbb E[Z_i\mid X_i=x_i]
$$
gives a soft assignment of $x_i$ to all clusters. A hard cluster assignment can be obtained by choosing the cluster with the largest posterior probability:
$$
\widehat C_i=\operatorname{arg\,max}_{1\le k\le K}
\gamma_{ik}.
$$
Explain the difference between soft clustering and hard clustering in this context.

---

5. Conditional Expectation of the Observation Given the Cluster:
Show that
$$
\mathbb E[X_i\mid C_i=k]=\mu_k.
$$
Explain why $\mu_k$ can be interpreted as the center of cluster $k$.
Then compare the two conditional expectations
$$
\mathbb E[Z_i\mid X_i=x_i]
$$
and
$$
\mathbb E[X_i\mid C_i=k].
$$
Explain why the first gives the soft cluster membership of an observed point, while the second gives the mean location of a cluster.

---

6. The Complete-Data Likelihood
If the latent labels $z_i$ were known, the complete-data likelihood would be
$$
p(x_1,\dots,x_n,z_1,\dots,z_n)=\prod_{i=1}^n
\prod_{k=1}^K
\left[
\phi_k
\mathscr N(x_i\mid \mu_k,\Sigma_k)
\right]^{z_{ik}}.
$$
Take the logarithm and show that the complete-data log-likelihood is
$$
\ell_c=\sum_{i=1}^n
\sum_{k=1}^K
z_{ik}
\left[
\log \phi_k
+
\log \mathscr N(x_i\mid \mu_k,\Sigma_k)
\right].
$$
Explain why this expression would be easy to maximize if the values of $z_{ik}$ were known.

---

7. The EM Interpretation:
In practice, the latent variables $Z_i$ are not observed. The EM algorithm replaces the unknown indicators $z_{ik}$ by their conditional expectations given the observed data and current parameter estimates:
$$
z_{ik}
\quad\leadsto\quad
\mathbb E[Z_{ik}\mid X_i=x_i].
$$
That is,
$$
z_{ik}
\quad\leadsto\quad
\gamma_{ik}.
$$
This is the E-step of the EM algorithm.
Using this idea, write the expected complete-data log-likelihood:
$$
Q=\sum_{i=1}^n
\sum_{k=1}^K
\gamma_{ik}
\left[
\log \phi_k
+
\log \mathscr N(x_i\mid \mu_k,\Sigma_k)
\right].
$$
Explain why the E-step can be interpreted as a conditional update of cluster membership probabilities.

---

8. Parameter Updates:
By maximizing $Q$ with respect to the model parameters, derive the standard GMM updates:
$$
N_k=\sum_{i=1}^n \gamma_{ik},
$$
$$
\phi_k^{\text{new}}=\frac{N_k}{n},
$$
$$
\mu_k^{\text{new}}=\frac{1}{N_k}
\sum_{i=1}^n
\gamma_{ik}x_i,
$$
and
$$
\Sigma_k^{\text{new}}=\frac{1}{N_k}
\sum_{i=1}^n
\gamma_{ik}
(x_i-\mu_k^{\text{new}})
(x_i-\mu_k^{\text{new}})^T.
$$
Explain how the responsibility $\gamma_{ik}$ acts as a fractional membership weight of observation $x_i$ in cluster $k$.

---

9. Interpretation:
Write a short paragraph explaining why GMM clustering can be viewed as a repeated process of conditional updating.
Your answer should mention the following points:

* The mixture weight $\phi_k$ is the prior probability of cluster $k$.
* The Gaussian density $\mathscr N(x_i\mid \mu_k,\Sigma_k)$ measures how compatible $x_i$ is with cluster $k$.
* The responsibility $\gamma_{ik}$ is the posterior probability of cluster $k$ after observing $x_i$.
* The soft assignment vector is
$$
\mathbb E[Z_i\mid X_i=x_i].
$$

* The M-step updates the cluster parameters using these posterior membership probabilities as weights.
Conclude that Gaussian mixture clustering is probabilistic clustering based on conditional expectations of latent cluster membership variables.

---

Here is a perfectly tailored question that you can add as the final part (**Part 10**) of your assignment notebook to bridge your theoretical derivations with your code implementation:

---

10. Computational Simulation and Out-of-Sample Validation

Using the theoretical framework established in the previous parts, write a Python class named `GMMFinancialSegmenter` that implements a two-dimensional Gaussian Mixture Model (GMM) using `scikit-learn` and visualizes the results interactively using `Plotly`. Your implementation should fulfill the following criteria:

* **Data Splitting and Scaling:** Accept a dataset containing two continuous features (e.g., mimicking financial behaviors like `PURCHASES` and `CREDIT_LIMIT`), standardize the features to handle variance scaling, and split the data into an 80% training set and a 20% validation/test set.
* **EM Execution:** Fit a GMM with $K=3$ components on the training data using the Expectation-Maximization (EM) algorithm, printing whether the model successfully converged and the number of iterations required.
* **Out-of-Sample Performance:** Compute and output the average log-likelihood score over the unseen test set to validate how well the learned density functions generalize to new data.
* **Interactive Visualizations:** Implement methods to generate three distinct Plotly figures:
1. An empirical **2D Density Heatmap** of the raw training data with marginal distributions to inspect its underlying multimodal structure.
2. A **Training Assignment Plot** that overlays the training data points on top of a continuous contour map showing the maximum posterior responsibilities ($\gamma_{ik}$) computed across a fine coordinate grid.
3. A **Test Assignment Plot** that replicates the contour boundary visualization but overlays out-of-sample test data points to expose the physical regions of cluster ambiguity.



Briefly evaluate the resulting plots. Explain how the continuous background contour map visually demonstrates the soft assignment expectation vector $\mathbb{E}[Z_i \mid X_i = x_{\text{grid}}]$ that you proved analytically in Part 3.

Use the dataset

https://www.kaggle.com/datasets/arjunbhasin2013/ccdata

### 1. Deriving the Marginal Density

**Proof**\
By the Law of Total Probability, the marginal probability density $p(\mathbf{x}_i)$ is obtained by summing the joint probability density over all possible mutually exclusive discrete states of the latent cluster variable $C_i$:$$p(\mathbf{x}_i) = \sum_{k=1}^{K} p(\mathbf{x}_i, C_i = k) = \sum_{k=1}^{K} P(C_i = k) \cdot p(\mathbf{x}_i \mid C_i = k)$$Substituting the prior cluster distribution $P(C_i = k) = \phi_k$ and the conditional multivariate Gaussian density $p(\mathbf{x}_i \mid C_i = k) = \mathcal{N}(\mathbf{x}_i \mid \boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k)$, we get:$$p(\mathbf{x}_i) = \sum_{k=1}^{K} \phi_k \mathcal{N}(\mathbf{x}_i \mid \boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k)$$

**Interpretation**\
This density is called a Gaussian mixture density because it is a convex linear combination ("mixture") of $K$ distinct component Gaussian distributions. The weights $\phi_k$ act as mixture proportions that scale each individual Gaussian component's contribution to the global probability landscape.

###2. Deriving the Posterior Cluster Probability
**Proof**\
By applying Bayes' rule directly to the conditional event $C_i = k$ given the observed evidence $\mathbf{X}_i = \mathbf{x}_i$, we have:$$P(C_i = k \mid \mathbf{X}_i = \mathbf{x}_i) = \frac{p(\mathbf{x}_i \mid C_i = k)P(C_i = k)}{p(\mathbf{x}_i)}$$Using the law of total probability derived in Part 1 to expand the denominator marginal density $p(\mathbf{x}_i)$, the relation becomes:$$P(C_i = k \mid \mathbf{X}_i = \mathbf{x}_i) = \frac{p(\mathbf{x}_i \mid C_i = k)P(C_i = k)}{\sum_{j=1}^{K} p(\mathbf{x}_i \mid C_i = j)P(C_i = j)}$$Substituting the respective parametric forms of the priors and likelihoods yields the responsibilities formula:$$\gamma_{ik} = P(C_i = k \mid \mathbf{X}_i = \mathbf{x}_i) = \frac{\phi_k \mathcal{N}(\mathbf{x}_i \mid \boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k)}{\sum_{j=1}^{K} \phi_j \mathcal{N}(\mathbf{x}_i \mid \boldsymbol{\mu}_j, \boldsymbol{\Sigma}_j)}$$

**Interpretation**\
The value $\gamma_{ik}$ represents a valid posterior probability because it is calculated after observing data sample $\mathbf{x}_i$. It maps the updated probability space bounded between $[0, 1]$ and dynamically satisfies $\sum_{k=1}^K \gamma_{ik} = 1$, representing our posterior belief regarding which latent component generated the point.

###3. One-Hot Encoding of the Latent Cluster Variable
**Proof**\
Since $Z_{ik}$ is a binary discrete Bernoulli indicator random variable taking values in $\{0,1\}$, its conditional expectation is directly equal to the probability of it evaluating to $1$:$$E[Z_{ik} \mid \mathbf{X}_i = \mathbf{x}_i] = 1 \cdot P(Z_{ik}=1 \mid \mathbf{X}_i = \mathbf{x}_i) + 0 \cdot P(Z_{ik}=0 \mid \mathbf{X}_i = \mathbf{x}_i)$$By definition, $Z_{ik} = 1 \iff C_i = k$, which leads to:$$E[Z_{ik} \mid \mathbf{X}_i = \mathbf{x}_i] = P(C_i = k \mid \mathbf{X}_i = \mathbf{x}_i) = \gamma_{ik}$$Stacking these scalar components into the full expectation vector matching the dimensions of $\mathbf{Z}_i$:$$E[\mathbf{Z}_i \mid \mathbf{X}_i = \mathbf{x}_i] = \begin{bmatrix} E[Z_{i1} \mid \mathbf{X}_i = \mathbf{x}_i] \\ E[Z_{i2} \mid \mathbf{X}_i = \mathbf{x}_i] \\ \vdots \\ E[Z_{iK} \mid \mathbf{X}_i = \mathbf{x}_i] \end{bmatrix} = \begin{bmatrix} \gamma_{i1} \\ \gamma_{i2} \\ \vdots \\ \gamma_{iK} \end{bmatrix}$$

**Conclusion**\
Therefore, the soft cluster assignment vector in a GMM is exactly equivalent to the mathematical conditional expectation of the structural latent indicator vector given the observed coordinates: $E[\mathbf{Z}_i \mid \mathbf{X}_i = \mathbf{x}_i]$.

###4. From Soft Assignment to Hard Clustering
Structural Differences

* Soft Clustering: Provides a continuous probabilistic profile distributed across all $K$ groups simultaneously via the responsibility vector $\boldsymbol{\gamma}_i$. It quantifies the model's structural uncertainty, allowing a single observation to exhibit split fractional membership between overlapping clusters.
* Hard Clustering: Imposes a strict deterministic assignment by collapsing the distribution onto a single distinct index map using the argmax operator: $\hat{C}_i = \arg\max_k \gamma_{ik}$. This discards uncertainty metrics and assumes an item belongs entirely to one source component.

###5. Conditional Expectation of the Observation Given the Cluster
**Proof**\
By using the properties of the multivariate Gaussian distribution, when conditioning on a specific cluster component $C_i = k$, the conditional expectation of $\mathbf{X}_i$ matches the center parameter of that individual sub-density:$$E[\mathbf{X}_i \mid C_i = k] = \int_{\mathbb{R}^d} \mathbf{x}_i \cdot \mathcal{N}(\mathbf{x}_i \mid \boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k) \, d\mathbf{x}_i = \boldsymbol{\mu}_k$$

Comparative Analysis
* $\boldsymbol{\mu}_k = E[\mathbf{X}_i \mid C_i = k]$: Maps from a discrete hidden group state to the continuous observation space, defining the true geometric center location of cluster component $k$.
* $\boldsymbol{\gamma}_i = E[\mathbf{Z}_i \mid \mathbf{X}_i = \mathbf{x}_i]$: Maps in the inverse direction—from a fixed continuous data observation back into the discrete simplex space of hidden cluster profiles, establishing fractional group membership.

###6. The Complete-Data Likelihood
**Proof**\
The complete-data likelihood function over all independent samples assuming hidden $\mathbf{z}_i$ elements are observed is:
$$p(\mathbf{X}, \mathbf{Z} \mid \boldsymbol{\phi}, \boldsymbol{\mu}, \boldsymbol{\Sigma}) = \prod_{i=1}^{n} \prod_{k=1}^{K} \left[ \phi_k \mathcal{N}(\mathbf{x}_i \mid \boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k) \right]^{z_{ik}}$$
Applying the strictly increasing monotonic natural logarithm converts the product operators into summations and isolates power coefficients:
$$\ell_c = \ln p(\mathbf{X}, \mathbf{Z} \mid \boldsymbol{\phi}, \boldsymbol{\mu}, \boldsymbol{\Sigma}) = \sum_{i=1}^{n} \sum_{k=1}^{K} z_{ik} \ln \left[ \phi_k \mathcal{N}(\mathbf{x}_i \mid \boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k) \right]$$Distributing the inner log across product components leaves:$$\ell_c = \sum_{i=1}^{n} \sum_{k=1}^{K} z_{ik} \left[ \ln \phi_k + \ln \mathcal{N}(\mathbf{x}_i \mid \boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k) \right]$$

**Optimization Advantage**\
If $\mathbf{z}_i$ indicators were known, optimization would uncouple across clusters. Instead of fitting a complex multi-modal mixture, we could collect the items assigned to cluster $k$ ($z_{ik}=1$) and optimize each cluster's parameters ($\boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k$) independently using standard isolated single-component Maximum Likelihood Estimation (MLE).
### 7. The EM Interpretation
**Expected Complete-Data Log-Likelihood**\
By replacing the unknown discrete indicator parameters $z_{ik}$ with their conditional expectations calculated during the E-step ($E[Z_{ik} \mid \mathbf{x}_i] = \gamma_{ik}$), the expected complete-data log-likelihood auxiliary function $Q$ is written as:
$$Q = \sum_{i=1}^{n} \sum_{k=1}^{K} \gamma_{ik} \left[ \ln \phi_k + \ln \mathcal{N}(\mathbf{x}_i \mid \boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k) \right]$$
**Conditional Update Interpretation**
The E-step acts as a conditional update because it keeps the cluster parameters fixed and updates our beliefs about the hidden cluster memberships. It combines our prior weights ($\phi_k$) with how well the current Gaussian parameters explain each data point ($\mathcal{N}(\mathbf{x}_i \mid \boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k)$) to compute an updated posterior distribution ($\gamma_{ik}$) for each item.

###8. Parameter Updates
**Derivation Strategy**\
To maximize $Q$ with respect to $\boldsymbol{\mu}_k$, we take the partial derivative of $Q$ and set it to zero. Expanding the Gaussian term focuses on the exponent component:$$\frac{\partial Q}{\partial \boldsymbol{\mu}_k} = \sum_{i=1}^{n} \gamma_{ik} \frac{\partial}{\partial \boldsymbol{\mu}_k} \left( -\frac{1}{2}(\mathbf{x}_i - \boldsymbol{\mu}_k)^T \boldsymbol{\Sigma}_k^{-1}(\mathbf{x}_i - \boldsymbol{\mu}_k) \right) = \sum_{i=1}^{n} \gamma_{ik} \boldsymbol{\Sigma}_k^{-1}(\mathbf{x}_i - \boldsymbol{\mu}_k) = \mathbf{0}$$Multiplying by $\boldsymbol{\Sigma}_k$ and expanding the summation reveals:$$\sum_{i=1}^{n} \gamma_{ik} \mathbf{x}_i - \sum_{i=1}^{n} \gamma_{ik} \boldsymbol{\mu}_k = \mathbf{0} \implies \boldsymbol{\mu}_k^{\text{new}} = \frac{\sum_{i=1}^{n} \gamma_{ik} \mathbf{x}_i}{\sum_{i=1}^{n} \gamma_{ik}} = \frac{1}{N_k}\sum_{i=1}^{n} \gamma_{ik} \mathbf{x}_i$$Similar derivations involving the derivative with respect to $\boldsymbol{\Sigma}_k$ and maximizing with respect to $\phi_k$ (subject to the equality constraint $\sum_k \phi_k = 1$ via Lagrange multipliers) yield the full set of M-step updates.\
**Role of Responsibilities**\
The responsibility $\gamma_{ik}$ acts as a fractional membership weight. Instead of an observation contributing exclusively to a single group, its impact is split across all $K$ clusters. A data point influences a cluster's new mean and covariance in direct proportion to its probability of belonging to that cluster ($\gamma_{ik}$).

###9. Core Interpretation
Gaussian Mixture Model clustering is fundamentally a process of repeated conditional updating that alternates between estimating hidden memberships and updating cluster profiles.

The mixture weight $\phi_k$ defines the prior probability of choosing cluster $k$. When a data point $\mathbf{x}_i$ is observed, the Gaussian density $\mathcal{N}(\mathbf{x}_i \mid \boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k)$ evaluates its structural compatibility with that cluster. Combining these two elements via Bayes' rule computes the responsibility $\gamma_{ik}$, which represents the updated posterior probability of cluster membership given the observed data. These responsibilities form the soft assignment expectation vector $E[\mathbf{Z}_i \mid \mathbf{X}_i = \mathbf{x}_i]$.

During the M-step, the model updates its cluster parameters ($\boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k, \phi_k$) by using these posterior probabilities as weights. This cycle forms a probabilistic framework that handles cluster overlap and uncertainty through the formal logic of conditional expectations.

###10. Computational Simulation and Out-of-Sample Validation
"""

import pandas as pd
import numpy as np
from sklearn.mixture import GaussianMixture
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import plotly.graph_objects as go
import plotly.express as px

class GMMFinancialSegmenter:
    def __init__(self, n_components=3, random_state=42):
        self.n_components = n_components
        self.random_state = random_state
        self.scaler = StandardScaler()
        self.model = GaussianMixture(n_components=n_components, random_state=random_state)

    def prepare_data(self, url):
        # Read dataset and isolate requested financial features
        df = pd.read_csv(url)
        raw_data = df[['PURCHASES', 'CREDIT_LIMIT']].dropna().values

        # Split into training (80%) and validation/test (20%) sets
        X_train_raw, X_test_raw = train_test_split(raw_data, test_size=0.20, random_state=self.random_state)

        # Scale to handle variance discrepancies
        self.X_train = self.scaler.fit_transform(X_train_raw)
        self.X_test = self.scaler.transform(X_test_raw)
        return self.X_train, self.X_test

    def fit_em(self):
        self.model.fit(self.X_train)
        print(f"--- EM Execution Status ---")
        print(f"Converged successfully: {self.model.converged_}")
        print(f"Number of iterations required: {self.model.n_iter_}")

    def evaluate_test(self):
        avg_log_likelihood = self.model.score(self.X_test)
        print(f"Average out-of-sample log-likelihood: {avg_log_likelihood:.4f}")
        return avg_log_likelihood

    def _generate_mesh_grid(self, resolution=150):
        # Create a bounding coordinate mesh covering the scaled data space
        x_min, x_max = self.X_train[:, 0].min() - 0.5, self.X_train[:, 0].max() + 0.5
        y_min, y_max = self.X_train[:, 1].min() - 0.5, self.X_train[:, 1].max() + 0.5
        xx, yy = np.meshgrid(np.linspace(x_min, x_max, resolution), np.linspace(y_min, y_max, resolution))
        mesh_points = np.c_[xx.ravel(), yy.ravel()]
        return xx, yy, mesh_points

    def plot_empirical_density(self):
        fig = px.density_heatmap(
            x=self.X_train[:, 0], y=self.X_train[:, 1],
            marginal_x="histogram", marginal_y="histogram",
            labels={'x': 'Scaled PURCHASES', 'y': 'Scaled CREDIT_LIMIT'},
            title="Figure 1: Empirical 2D Density Heatmap (Training Set)",
            template="plotly_dark"
        )
        fig.show()

    def plot_assignments(self, data_type="train"):
        data_matrix = self.X_train if data_type == "train" else self.X_test
        xx, yy, mesh_points = self._generate_mesh_grid()

        # Predict continuous posterior responsibilities over the grid
        responsibilities = self.model.predict_proba(mesh_points)
        max_resp = np.max(responsibilities, axis=1).reshape(xx.shape)

        # Hard predictions for the background scatter point overlays
        point_labels = self.model.predict(data_matrix)

        # Build interactive layout
        fig = go.Figure()

        # Overlay background contour mapping maximum posterior capability
        fig.add_trace(go.Contour(
            x=np.linspace(xx.min(), xx.max(), xx.shape[1]),
            y=np.linspace(yy.min(), yy.max(), xx.shape[0]),
            z=max_resp,
            colorscale='Viridis',
            contours_coloring='heatmap',
            line_width=0,
            opacity=0.75,
            colorbar=dict(title="Max Responsibility")
        ))

        # Overlay discrete scatter data points
        for cluster_idx in range(self.n_components):
            mask = point_labels == cluster_idx
            fig.add_trace(go.Scatter(
                x=data_matrix[mask, 0], y=data_matrix[mask, 1],
                mode='markers', name=f'Cluster {cluster_idx}',
                marker=dict(size=5, line=dict(width=0.5, color='white'))
            ))

        title_text = "Figure 2: Training Soft Assignment Profile" if data_type == "train" else "Figure 3: Out-of-Sample Test Assignment Profile"
        fig.update_layout(
            title=title_text, xaxis_title="Scaled PURCHASES", yaxis_title="Scaled CREDIT_LIMIT",
            template="plotly_dark"
        )
        fig.show()

# Execution Pipeline
# NOTE: the original aditya-bhatt/Credit-Card-Customer-Segmentation URL returns a
# 404 (repo/path doesn't serve that file). Swapped in a mirror that actually
# serves the raw CC GENERAL.csv.
url = "https://raw.githubusercontent.com/RAHULKASHYAP02/Credit-Card-Segmentation/master/CC%20GENERAL.csv"
segmenter = GMMFinancialSegmenter(n_components=3)
X_train, X_test = segmenter.prepare_data(url)

segmenter.fit_em()
segmenter.evaluate_test()

# Display interactive Plotly figures
segmenter.plot_empirical_density()
segmenter.plot_assignments("train")
segmenter.plot_assignments("test")